## simple dockerfile for downloading files

FROM python:3.10

WORKDIR /app

COPY meteodata/requirements.txt .

RUN pip install -r requirements.txt

COPY meteodata/ .

EXPOSE 8080

CMD ["uvicorn", "meteodata.download_mf_tools.api:app", "--host", "0.0.0.0", "--port", "8080"]